// src/components/Button.tsx
import React from 'react';
import { ButtonProps } from '../../types/tokens';
import { useTheme } from '../theme/useTheme';

export const Button: React.FC<ButtonProps> = ({
  children,
  variant = 'default',
  size = 'default',
  disabled = false,
  type = 'button',
  onClick,
  'data-testid': dataTestId,
  'aria-label': ariaLabel,
  className = '',
}) => {
  const { tokens } = useTheme();
  
  const getVariantStyles = () => {
    switch (variant) {
      case 'default':
        return {
          background: tokens['color.primary'] as string || '#d45a5f',
          color: tokens['color.primary-foreground'] as string || '#ffffff',
        };
      case 'destructive':
        return {
          background: tokens['color.destructive'] as string || '#e05a3f',
          color: tokens['color.destructive-foreground'] as string || '#ffffff',
        };
      case 'outline':
        return {
          background: 'transparent',
          color: tokens['color.primary'] as string || '#d45a5f',
          border: `1px solid ${tokens['color.primary'] as string || '#d45a5f'}`,
        };
      case 'secondary':
        return {
          background: tokens['color.card'] as string || '#f8f9ef',
          color: tokens['color.foreground'] as string || '#777777',
        };
      case 'ghost':
        return {
          background: 'transparent',
          color: tokens['color.primary'] as string || '#d45a5f',
        };
      case 'link':
        return {
          background: 'transparent',
          color: tokens['color.primary'] as string || '#d45a5f',
          textDecoration: 'underline',
          padding: 0,
        };
      default:
        return {
          background: tokens['color.primary'] as string || '#d45a5f',
          color: tokens['color.primary-foreground'] as string || '#ffffff',
        };
    }
  };

  const variantStyles = getVariantStyles();
  const radius = tokens['radius.default'] as string || '0.5rem';

  const sizeStyles = {
    default: { padding: '0.5rem 1rem', fontSize: tokens['font-size.body'] as string || '1rem' },
    sm: { padding: '0.25rem 0.75rem', fontSize: tokens['font-size.caption'] as string || '0.875rem' },
    lg: { padding: '0.75rem 1.5rem', fontSize: tokens['font-size.heading-2'] as string || '1.5rem' },
    icon: { padding: '0.5rem', fontSize: tokens['font-size.body'] as string || '1rem' },
  };

  const btnStyle: React.CSSProperties = {
    ...variantStyles,
    borderRadius: radius,
    ...(variant === 'link' ? {} : sizeStyles[size]),
    border: variant === 'outline' ? variantStyles.border : 'none',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: tokens['typography.font-sans'] as string || 'system-ui',
    opacity: disabled ? 0.5 : 1,
    transition: 'all 0.2s ease',
    fontWeight: 500,
  };

  return (
    <button
      type={type}
      style={btnStyle}
      onClick={onClick}
      disabled={disabled}
      data-testid={dataTestId}
      aria-label={ariaLabel}
      className={className}
    >
      {children}
    </button>
  );
};

export default Button;

// src/svelte/Button.svelte
<script lang="ts">
  import tokens from '../../dist/js/theme.js';
  import darkTokens from '../../dist/js/theme.dark.js';

  export let variant: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link' = 'default';
  export let size: 'default' | 'sm' | 'lg' | 'icon' = 'default';
  export let disabled: boolean = false;
  export let onclick: (event: MouseEvent) => void = () => {};

  let mode: 'light' | 'dark' = 'light';

  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('yyc3-theme');
    if (stored === 'light' || stored === 'dark') {
      mode = stored;
    } else {
      mode = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
  }

  $: currentTokens = mode === 'dark' ? darkTokens : tokens;

  $: buttonStyle = (() => {
    const styles: Record<string, string> = {
      padding: '0.5rem 1rem',
      borderRadius: currentTokens.radius?.md || currentTokens.radius?.md?.value || '0.25rem',
      border: 'none',
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.5 : 1,
      fontSize: currentTokens['font-size']?.body || currentTokens['font-size']?.body?.value || '1rem',
      fontFamily: currentTokens.typography?.['font-sans'] || currentTokens.typography?.['font-sans']?.value || 'system-ui',
      transition: 'all 0.2s ease',
    };

    switch (variant) {
      case 'default':
        styles.backgroundColor = currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f';
        styles.color = currentTokens.color?.primary?.foreground || '#fff';
        break;
      case 'destructive':
        styles.backgroundColor = currentTokens.color?.destructive?.hex || currentTokens.color?.destructive?.value?.hex || '#e05a3f';
        styles.color = currentTokens.color?.destructive?.foreground || '#fff';
        break;
      case 'outline':
        styles.backgroundColor = 'transparent';
        styles.color = currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f';
        styles.border = `1px solid ${currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f'}`;
        break;
      case 'secondary':
        styles.backgroundColor = currentTokens.color?.['muted-foreground'] || '#ccc';
        styles.color = currentTokens.color?.background?.hex || currentTokens.color?.background?.value?.hex || '#fbfbfc';
        break;
      case 'ghost':
        styles.backgroundColor = 'transparent';
        styles.color = currentTokens.color?.foreground || '#000';
        break;
      case 'link':
        styles.backgroundColor = 'transparent';
        styles.color = currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f';
        styles.textDecoration = 'underline';
        styles.padding = '0';
        break;
    }

    switch (size) {
      case 'sm':
        styles.padding = '0.25rem 0.5rem';
        styles.fontSize = '0.875rem';
        break;
      case 'lg':
        styles.padding = '0.75rem 1.5rem';
        styles.fontSize = '1.125rem';
        break;
      case 'icon':
        styles.padding = '0.5rem';
        break;
    }

    return styles;
  })();

  const handleClick = (event: MouseEvent) => {
    if (!disabled) {
      onclick(event);
    }
  };
</script>

<button
  style={buttonStyle}
  {disabled}
  on:click={handleClick}
>
  <slot />
</button>
