// src/components/Input.tsx
import React from 'react';
import { InputProps } from '../../types/tokens';
import { useTheme } from '../theme/useTheme';

export const Input: React.FC<InputProps> = ({
  type = 'text',
  label,
  placeholder = '',
  disabled = false,
  value,
  onChange,
  required = false,
  name,
  'data-testid': dataTestId,
  className = '',
}) => {
  const { tokens } = useTheme();
  const radius = tokens['radius.md'] as string || '0.25rem';
  const focusShadowValue = tokens['shadow.focus'] as string;
  const focusShadow = focusShadowValue ? focusShadowValue.split(' ') : ['0px', '0px', '0px', '2px', '#e06a70'];
  const shadowString = `${focusShadow[0]} ${focusShadow[1]} ${focusShadow[2]} ${focusShadow[3]} ${focusShadow[4] || '#e06a70'}`;

  const inputStyle: React.CSSProperties = {
    padding: '0.5rem 0.75rem',
    borderRadius: radius,
    border: `1px solid ${tokens['color.muted-foreground'] as string || '#ccc'}`,
    fontSize: tokens['font-size.body'] as string || '1rem',
    fontFamily: tokens['typography.font-sans'] as string || 'system-ui',
    lineHeight: tokens['line-height.body'] as string || '1.5',
    color: tokens['color.foreground'] as string || '#000',
    backgroundColor: tokens['color.background'] as string || '#fff',
    opacity: disabled ? 0.5 : 1,
    cursor: disabled ? 'not-allowed' : 'text',
    transition: 'all 0.2s ease',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };

  const handleFocus = (e: React.FocusEvent<HTMLInputElement>) => {
    e.target.style.borderColor = tokens['color.primary'] as string || '#d45a5f';
    e.target.style.boxShadow = shadowString;
  };

  const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
    e.target.style.borderColor = tokens['color.muted-foreground'] as string || '#ccc';
    e.target.style.boxShadow = 'none';
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (onChange) {
      onChange(e.target.value);
    }
  };

  return (
    <div>
      {label && <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem', fontWeight: 500 }}>{label}</label>}
      <input
        type={type}
        placeholder={placeholder}
        disabled={disabled}
        value={value}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        required={required}
        name={name}
        data-testid={dataTestId}
        style={inputStyle}
        className={className}
      />
    </div>
  );
};

export default Input;

// src/svelte/Input.svelte
<script lang="ts">
  import tokens from '../../dist/js/theme.js';
  import darkTokens from '../../dist/js/theme.dark.js';

  export let type: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' = 'text';
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let value: string = '';
  export let oninput: (event: Event) => void = () => {};

  let mode: 'light' | 'dark' = 'light';

  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('yyc3-theme');
    if (stored === 'light' || stored === 'dark') {
      mode = stored;
    } else {
      mode = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
  }

  $: currentTokens = mode === 'dark' ? darkTokens : tokens;

  $: inputStyle = {
    width: '100%',
    padding: '0.5rem 0.75rem',
    borderRadius: currentTokens.radius?.md || currentTokens.radius?.md?.value || '0.25rem',
    border: `1px solid ${currentTokens.color?.['muted-foreground'] || '#ccc'}`,
    backgroundColor: currentTokens.color?.background?.hex || currentTokens.color?.background?.value?.hex || '#fbfbfc',
    color: currentTokens.color?.foreground || '#000',
    fontSize: currentTokens['font-size']?.body || currentTokens['font-size']?.body?.value || '1rem',
    fontFamily: currentTokens.typography?.['font-sans'] || currentTokens.typography?.['font-sans']?.value || 'system-ui',
    opacity: disabled ? 0.5 : 1,
    transition: 'all 0.2s ease',
    outline: 'none',
  };

  const handleFocus = (event: FocusEvent) => {
    const target = event.target as HTMLInputElement;
    target.style.borderColor = currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f';
    target.style.boxShadow = `0 0 0 3px ${currentTokens.color?.primary?.hex || currentTokens.color?.primary?.value?.hex || '#d45a5f'}40`;
  };

  const handleBlur = (event: FocusEvent) => {
    const target = event.target as HTMLInputElement;
    target.style.borderColor = inputStyle.border;
    target.style.boxShadow = 'none';
  };
</script>

<input
  {type}
  {placeholder}
  {disabled}
  {value}
  style={inputStyle}
  on:input={oninput}
  on:focus={handleFocus}
  on:blur={handleBlur}
/>
