// src/components/Checkbox.tsx
import React, { useState } from 'react';
import { useTheme } from '../theme/useTheme';

interface CheckboxProps {
  checked?: boolean;
  disabled?: boolean;
  onChange?: (checked: boolean) => void;
  children?: React.ReactNode;
  className?: string;
}

export const Checkbox: React.FC<CheckboxProps> = ({
  checked = false,
  disabled = false,
  onChange,
  children,
  className = '',
}) => {
  const { tokens } = useTheme();
  const [internalChecked, setInternalChecked] = useState(checked);
  const isControlled = checked !== undefined;
  const isChecked = isControlled ? checked : internalChecked;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newChecked = e.target.checked;
    if (!isControlled) {
      setInternalChecked(newChecked);
    }
    if (onChange) {
      onChange(newChecked);
    }
  };

  const checkboxStyle: React.CSSProperties = {
    width: '1.25rem',
    height: '1.25rem',
    borderRadius: (tokens['radius.sm'] as string) || '0.125rem',
    border: `2px solid ${(tokens['color.muted-foreground'] as string) || '#ccc'}`,
    backgroundColor: isChecked ? (tokens['color.primary'] as string) || '#d45a5f' : 'transparent',
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.5 : 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  };

  const checkmarkStyle: React.CSSProperties = {
    color: (tokens['color.primary-foreground'] as string) || '#fff',
    fontSize: '0.875rem',
    fontWeight: 'bold',
    display: isChecked ? 'block' : 'none',
  };

  const labelStyle: React.CSSProperties = {
    marginLeft: '0.5rem',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontSize: (tokens['font-size.body'] as string) || '1rem',
    fontFamily: (tokens['typography.font-sans'] as string) || 'system-ui',
    color: (tokens['color.foreground'] as string) || '#000',
  };

  return (
    <label
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        cursor: disabled ? 'not-allowed' : 'pointer',
      }}
      className={className}
    >
      <div style={checkboxStyle}>
        <span style={checkmarkStyle}>✓</span>
      </div>
      <input
        type="checkbox"
        checked={isChecked}
        disabled={disabled}
        onChange={handleChange}
        style={{ position: 'absolute', opacity: 0, cursor: disabled ? 'not-allowed' : 'pointer' }}
      />
      {children && <span style={labelStyle}>{children}</span>}
    </label>
  );
};

export default Checkbox;

// src/vue/Checkbox.vue
<script setup lang="ts">
import { computed } from 'vue';
import tokens from '../../dist/js/theme.js';
import darkTokens from '../../dist/js/theme.dark.js';

interface Props {
  modelValue?: boolean;
  disabled?: boolean;
  indeterminate?: boolean;
  label?: string;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
  disabled: false,
  indeterminate: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const mode = computed(() => {
  if (typeof window === 'undefined') return 'light';
  const stored = localStorage.getItem('yyc3-theme');
  if (stored === 'light' || stored === 'dark') {
    return stored;
  }
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
});

const currentTokens = computed(() => mode.value === 'dark' ? darkTokens : tokens);

const checkboxStyle = computed(() => {
  const styles: Record<string, string> = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: props.disabled ? 'not-allowed' : 'pointer',
    opacity: props.disabled ? 0.5 : 1,
    fontSize: currentTokens.value['font-size.body'] as string || '1rem',
    fontFamily: currentTokens.value['typography.font-sans'] as string || 'system-ui',
  };

  return styles;
});

const inputStyle = computed(() => {
  const styles: Record<string, string> = {
    width: '1.125rem',
    height: '1.125rem',
    borderRadius: currentTokens.value['radius.sm'] as string || '0.25rem',
    border: `2px solid ${currentTokens.value['color.primary'] as string || '#d45a5f'}`,
    backgroundColor: props.modelValue ? currentTokens.value['color.primary'] as string || '#d45a5f' : 'transparent',
    cursor: props.disabled ? 'not-allowed' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  };

  return styles;
});

const checkStyle = computed(() => ({
  color: '#fff',
  fontSize: '0.75rem',
  fontWeight: 'bold',
  display: props.modelValue ? 'block' : 'none',
}));

const labelStyle = computed(() => ({
  color: currentTokens.value['color.foreground'] as string || '#000',
}));

const handleClick = () => {
  if (!props.disabled) {
    emit('update:modelValue', !props.modelValue);
  }
};
</script>

<template>
  <div :style="checkboxStyle" @click="handleClick">
    <div :style="inputStyle">
      <span v-if="modelValue" :style="checkStyle">✓</span>
    </div>
    <span v-if="label" :style="labelStyle">{{ label }}</span>
  </div>
</template>
<style scoped>
input {
  display: none;
}
</style>
